a="python programming"
print(a.upper())
print(a.lower())
print(a.capitalize())
print(a.title())
print(a.isdigit())
print(a.isalpha())
print(a.isalnum())
print(a.index('g'))
print(a.count('m'))
print(a.split())
